inherit_from: config/default.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety

Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
