version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "silvercop.gemspec" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "silvercop.gemspec" }}

      - run:
          name: Setup RubyGems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: Build gem
          command: |
            gem build silvercop.gemspec

      - run:
          name: Publish package
          command: |
              gem push "silvercop-$(git describe --tags).gem"

workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
